"use strict";

// tests for message
// Generated by serverless-jest-plugin

const mod = require("./../src/message");

const jestPlugin = require("serverless-jest-plugin");
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "handler" });

describe("message", () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it("Message should return 200", () => {
    return wrapped.run({}).then((response) => {
      expect(response).toBeDefined();
      expect(response.statusCode).toBe(200);
    });
  });
});
